// <auto-generated />
namespace Inventario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newRecors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newRecors));
        
        string IMigrationMetadata.Id
        {
            get { return "202302021059142_newRecors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
